### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by anton-kazlouski** [greyfenrir/cargo#1]
Hello! Thanks for your time and efforts. You can find some comments about the homework below.

BE
1. No migrations in the repo.
2. CORS_ORIGIN_WHITELIST = ["http://localhost:8080"] -- in my case I had to modify it because 8080 was already occupied.
3. It would be nice to see a bit more complex db schema
4. back.api.test.test_api.APITest.test_get_user_list:29 -- It appears unclear to me. The obtained username is compared to the admin or user. But 'owner' key is used for self.fail statement. I would just omit that 'else' block as it is redundant. If a test fails, let it fail and then investigate the issue.
5. back.api.test.test_api.APITest.test_get_user_details:39 -- it might happen that id would become different
6. back.api.test.test_api.APITest.test_get_shipment_list -- again, if a test fails, let it fail, I don't see a need to use self.fail statement. Just compare the actual response with expected.
7. back.api.test.test_api.APITest.test_add_shipment -- It might be best to divide this test into two parts: creation and permissions. Additionaly, usually you want to make sure that response code is what was expected and then verify that content is in db.
8. len(Shipment.objects.all()) -- Shipment.objects.count()
9. self.assertGreaterEqual(response.status_code, 400) -- why not just self.assertEqual?
10. back.api.test.test_api.APITest.test_delete_shipment -- why 300 code for delete? I think the default is 204

FE
1. What's the reason of using jquery's ajax?
2. No error handling. A user should be notified if something is wrong.

Summary:
I appreciate how the code is organized and not overly confusing, especially the FE section. However, I would expect slightly more advanced methods for testing and model structure.

Please feel free to tackle the issues listed above If you are willing to so. However, I don't want to raise false expectations, so just be aware that our partners are looking for middle+ level.

Do not hesitate to request clarifications on my comments.

**Comment by greyfenrir** [comment]
1. fixed
2. should I turn CORS_ORIGIN_ALLOW_ALL on?

**Comment by greyfenrir** [comment]
4-6: fixed

**Comment by greyfenrir** [comment]
8. fixed
9. 4xx as 'client error'
10. 2xx as 'success'

**Comment by anton-kazlouski** [comment]
> should I turn CORS_ORIGIN_ALLOW_ALL on?

I see 3 ways how to handle this. The one you mentioned. I would check if DEBUG is enabled, if yes, then allow all cors origin requests, otherwise use different setting. Another way is to have multiple settings files for dev, test, prod or whatever environment. One more alternative is to just add some notes regarding CORS_ORIGIN_ALLOW_ALL parameter in README.

**Comment by anton-kazlouski** [comment]
> No migrations in the repo.

What I meant is that migrations should come with the project. This kind of a flag that you are not well familiar with ORM part of the Django. Which is a must.

> it might happen that id would become different

You've fixed for user id, but what about foreign keys of shipments?


I think we can stop here. You've done a good job, however, as I mentioned our expectations are middle+. The results of your homework highlighted a certain gaps in areas that are crucial to us.
Appreciate your time and efforts. Wish you luck in finding your dream company :)

**Comment by greyfenrir** [comment]
Got it. Thanks for your time and advises.
